name=Servo_TinyCore
version=1.1.2
author=Michael Margolis, Arduino
maintainer=MCUdude
sentence=Allows TinyCore supported parts to control a variety of servo motors. This is a renamed copy so user can force the IDE to use the core-associated library.
paragraph=If the Servo library has been installed into <sketchbook>/libraries, it will be used instead. It probably doesn't support the TinyCore devices. In this case, use Servo_TinyCore.h instead of Servo.h. This library can control 12 servos using only 1 timer.
category=Device Control
url=https://www.arduino.cc/reference/en/libraries/servo/
architectures=avr,sam,samd
